version: '3.3'

services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'smarkiodb'
            MYSQL_USER: 'watson'
            MYSQL_PASSWORD: 'tts@test'
            MYSQL_ROOT_PASSWORD: '1234'
            MYSQL_TCP_PORT: 3307
        ports:
            - '3307:3307'
        expose: 
            - '3307'